### PR TITLE
[DRAFT] Explore using type-safe planning metadata

### PR DESCRIPTION
**Pull request by joshuatcasey**
## Summary
[DRAFT] Explore using type-safe planning metadata

## Use Cases
Helps a bit with type safety and clarity of purpose

## Checklist
* [ ] I have viewed, signed, and submitted the Contributor License Agreement.
* [ ] I have linked issue(s) that this PR should close using keywords or the Github UI (See [docs](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue))
* [ ] I have added an integration test, if necessary.
* [ ] I have reviewed the [styleguide](https://github.com/paketo-buildpacks/community/blob/main/STYLEGUIDE.md) for guidance on my code quality.
* [ ] I'm happy with the commit history on this PR (I have rebased/squashed as needed).

### CODE REVIEW

**Comment by ForestEckhardt** [comment]
@joshuatcasey Bump

**Comment by joshuatcasey** [comment]
Closing. This was to demo https://github.com/paketo-buildpacks/packit/pull/331.

**Comment by ForestEckhardt** [comment]
@joshuatcasey Do you want me to close this?

**Comment by joshuatcasey** [comment]
Whoops. I got it.

**Pull request closed without merging**
