### PR TITLE
Allow Roll Forward Behavior to be Disabled (via `BP_DOTNET_ROLL_FORWARD=Disable`)

### PR DESCRIPTION
**Pull request by joshuatcasey**
## Summary

Closes paketo-buildpacks/dotnet-core#385

## Checklist

* [x] I have viewed, signed, and submitted the Contributor License Agreement.
* [x] I have linked issue(s) that this PR should close using keywords or the Github UI (See [docs](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue))
* [x] I have added an integration test, if necessary.
* [x] I have reviewed the [styleguide](https://github.com/paketo-buildpacks/community/blob/main/STYLEGUIDE.md) for guidance on my code quality.
* [x] I'm happy with the commit history on this PR (I have rebased/squashed as needed).

### CODE REVIEW

**Comment by ForestEckhardt** [comment]
The name on this PR is a little confusing. Is this meant to still be a draft?

**Comment by fg-j** [comment]
Ping @joshuatcasey - what's your intent with this PR? Draft or review-ready?

**Comment by joshuatcasey** [comment]
The PR is ready for review. I've removed `[DRAFT]` from the title.

**Comment by fg-j** [comment]
Hey @joshuatcasey I'm wondering what makes this change patch-sized versus minor-sized. Certainly a small change, but it does add a feature – a configuration option. Would you be open to marking this `semver:minor`?

Otherwise, the implementation looks great!

**Comment by joshuatcasey** [comment]
@fg-j I agree, `minor` is appropriate. Not sure what the thought process was when selecting `patch.

**Review by fg-j — APPROVED** [review]

**Comment by fg-j** [comment]
@joshuatcasey Please file an issue to document this on the website!

**Comment by joshuatcasey** [comment]
> @joshuatcasey Please file an issue to document this on the website!

@fg-j do you mean add this env variable to https://paketo.io/docs/reference/dotnet-core-reference/?

**Pull request merged**
