### PR TITLE
Adds support for layer style SBOM

### LINKED ISSUE #285: Generate SBOM for .NET Core Runtime
To implement [Paketo RFC0038](https://github.com/paketo-buildpacks/rfcs/blob/932d89a970bea06c002496dbd6c7e3812ccab788/text/0038-cdx-syft-sbom.md), this buildpack will need to move from storing SBOM information in layer metadata to storing it in files that the CNB lifecycle can manipulate during the build. The RFC outlines what these files are and what they should contain.

Changes to this buildpack will include:
- Bump to Buildpack API 0.7
- Use packit v2.0.1
- We may need to add a `name` field to the `dotnet-runtime` dependency dep-server metadata and the buildpack.toml so that this field is populated in the BOM

### PR DESCRIPTION
**Pull request by ForestEckhardt**
- Adds name field to the dependency
- Removes custom logger in favor of higher level scribe.Emitter

Resolves #285 

## Checklist

* [x] I have viewed, signed, and submitted the Contributor License Agreement.
* [x] I have linked issue(s) that this PR should close using keywords or the Github UI (See [docs](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue))
* [x] I have added an integration test, if necessary.
* [x] I have reviewed the [styleguide](https://github.com/paketo-buildpacks/community/blob/main/STYLEGUIDE.md) for guidance on my code quality.
* [x] I'm happy with the commit history on this PR (I have rebased/squashed as needed).

### CODE REVIEW

**Comment by fg-j** [comment]
In the investigation of SBOM support, ccheetham found that syft can actually extract info from the .NET runtime itself. See the ".NET Framework support" section of [this comment](https://github.com/paketo-buildpacks/dotnet-core/issues/712#issuecomment-1137641445). I'm wondering if, for this dependency, we can actually use syft "for real" to get a more complete and accurate SBOM.

**Comment by ForestEckhardt** [comment]
@fg-j After our conversation and re-reading of the attached comment, I will test using a syft package scan as opposed to the generate from dependency call and report back my findings.

**Comment by ForestEckhardt** [comment]
@fg-j I tried the path shown in the comment with `sbom.Generate()` and seemingly no useful information was generated.

**Comment by ForestEckhardt** [comment]
I might purpose that we move forward with generating the SBOM from the dependency and if we discover that we can leverage Syft in the future we can easily upgrade it to do so.

**Review by sophiewigmore — APPROVED** [review]

**Review by fg-j — APPROVED** [review]

**Pull request merged**
